### PR TITLE
[#99] Delete System.version & set elixir as ">= 1.7.4"

### PR DESCRIPTION
**Pull request by davecaos**
Delete `System.version` from mix.exs template and set elixir as ">= 1.7.4" to match the fixed version at Dockerfile template.
image

### CODE REVIEW

**Comment by CrowdHailer** [comment]
Can you add a bit more information on why this is the right thing to do.

**Comment by davecaos** [comment]
Sure! 
The last time I used raxx_kit to scaffold Ace server I had to change by hand the elixir version in the mix.exs and dockerfiles to 1.9.4, also I realized that there less version available at docker hub than I expected.
Now I am no sure if this is the righ thing to do. At least  set it to 1.7.4 or greater it tackle the problem in a simpler manner, but delegate responsibility to the raxx_kit's user to care about the mix configuration.

Another option could be a flag to set fixed version like `--elixir_version x.x.x`.

**Comment by CrowdHailer** [comment]
I think the thing to do is update the value in the dockerfile to the latest value. and leave the mix file to use the elixir version that generated it

**Comment by davecaos** [comment]
Ah OK! the `System.version` value is for set  the elixir version that generated the server, not for only match the Elixir version that user it is using at the moment.
I will update this PR with **only** changing the Elixir version to 1.10.2 in the Dockerfile

**Comment by CrowdHailer** [comment]
Thanks, btw I hadn't reread the issue #99 now I've remembered there are a bunch of caveats doing anything cleverer. This is a helpful bump on the docker file.

Can you add a changelog entry with todays date and I can push it as 12.2

**Comment by davecaos** [comment]
> Thanks, btw I hadn't reread the issue #99 now I've remembered there are a bunch of caveats doing anything cleverer. This is a helpful bump on the docker file.
> 
> Can you add a changelog entry with todays date and I can push it as 12.2
Done !
image

**Comment by CrowdHailer** [comment]
published. thanks :whale: 

Leave a update on the forum if you fancy it. https://elixirforum.com/t/raxx-kit-micro-framework-for-web-applications/13805/19

**Pull request merged**
